esphome:
  name: esphome-${device_name}
  friendly_name: ESPHome ${device_friendly_name}
  comment: ${comment}
  
esp32:
  board: nodemcu-32s2
  variant: esp32s2
  framework:
    type: arduino

logger:

api:
    
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Esphome-${device_friendly_name}
    password: !secret ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: ${device_friendly_name} WiFi Signal
    update_interval: 60s

switch:
  - platform: gpio
    name: ${device_friendly_name} Board LED
    id: board_led
    pin:
      number: GPIO2
      inverted: true