esphome:
  name: esphome-${device_name}
  friendly_name: ESPHome ${device_friendly_name}
  comment: ${comment}
  
esp8266:
  board: esp12e

logger:

api:
    
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_friendly_name}
    password: !secret ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: ${device_friendly_name} WiFi Signal
    update_interval: 60s

switch:
  - platform: gpio
    name: ${device_friendly_name} Board LED
    id: board_led
    pin:
      number: GPIO2
      inverted: true